// File generated by FlutterFire CLI.
// This file is used to configure Firebase for your Flutter app.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNYPK5lxAHeYtN0r260M6vm6aVNbLQ3f0',
    appId: '1:382983488421:android:a505ae6e3ffde7ed9f1e4c',
    messagingSenderId: '382983488421',
    projectId: 'thegardenhelper-35b52',
    storageBucket: 'thegardenhelper-35b52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgzt3Ab5sRSlAV09gOqkvw2ATaruBKOqs',
    appId: '1:382983488421:ios:20890b6fa8ad37279f1e4c',
    messagingSenderId: '382983488421',
    projectId: 'thegardenhelper-35b52',
    storageBucket: 'thegardenhelper-35b52.firebasestorage.app',
    iosClientId: '382983488421-mob39d61etlt0vsjq10aafr7dfhqeuik.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}