// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwyL3PbGnr5ZwYz-GadsMzIKXy6FMxa7g',
    appId: '1:382983488421:web:6c849e1f898ada969f1e4c',
    messagingSenderId: '382983488421',
    projectId: 'thegardenhelper-35b52',
    authDomain: 'thegardenhelper-35b52.firebaseapp.com',
    storageBucket: 'thegardenhelper-35b52.firebasestorage.app',
    measurementId: 'G-F1CRTREDPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNYPK5lxAHeYtN0r260M6vm6aVNbLQ3f0',
    appId: '1:382983488421:android:a505ae6e3ffde7ed9f1e4c',
    messagingSenderId: '382983488421',
    projectId: 'thegardenhelper-35b52',
    storageBucket: 'thegardenhelper-35b52.firebasestorage.app',
  );
}
